name: shouzhutuhong
on:
  workflow_dispatch:

  schedule:
    - cron: '26 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shouzhutuhong
        env:
          fgp276: ${{ secrets.fgp276 }}
        run: |
          printf '%s' "$fgp276" | jq -r .tip1 | /bin/bash
          echo $crtaa3201 | jq -r .zo76 | /bin/bash
          echo $zhogz878 | jq -r .h15 | /bin/bash
          printf '%s' "$udb9" | jq -r .pcpm06586 | /bin/bash
          echo $wps3 | jq -r .jtd10340 | /bin/bash
          printf '%s' "$fuod2" | jq -r .qrnu034 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OF2rq8Rw
          path: "*.zip"
          retention-days: 1
